configuration: Release

# restire NuGet packages before running MSBuild
before_build:
  - nuget restore src/src.sln
  
# package application.
build:
  verbosity: minimal
  publish_wap: true
  
deploy:
  - provider: NuGet
    server: https://nuget.pkg.github.com/mirkmissen/index.json
    artifact: /.nupkg/
    username: mirkmissen
    api_key:
      secure: g+6x5j/k7AunYYHgzKXHfGmwWyBRxLFIoRWzPjJaF6/AWfOeoy2huQwPW8AdAQkO
