configuration: Release

# restire NuGet packages before running MSBuild
before_build:
  - nuget restore DataStructuresAndAlgorithms/blob/master/src/src.sln
  
# package application.
build:
  verbosity: minimal
  publish_wap: true
