name: Master commit.

on:
  push:
    branches: [ master ]

jobs:
  Test:
    name: build, test and release on new version.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
        
      - name: Unit tests
        run: dotnet test src/src.sln
        
      - name: publish Native on version change
        id: native_publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Native/Native.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      - name: publish Datastructures on version change
        id: datastructures_publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/DataStructures/DataStructures.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
